name: Docker Alpine
on:
  push:
    branches:
    - "main"
    - "core-8-branch"
    - "core-8-6-branch"
    - "docker-build"
    tags:
    - "core-**"
permissions:
  contents: read
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Prepare
        run: |
          touch tclStubInit.c tclOOStubInit.c tclOOScript.h
        working-directory: generic

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: mbwagner/tcl:alpine mbwagner/tcl:${{ env.TCL_PATCHLEVEL }}-alpine
        
