name: Docker Alpine
on:
  push:
    branches:
    - "main"
    - "core-8-branch"
    - "core-8-6-branch"
    - "docker-build"
    tags:
    - "core-**"
permissions:
  contents: read
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        timeout-minutes: 5
      - name: Prepare
        run: |
          touch tclStubInit.c tclOOStubInit.c tclOOScript.h
        working-directory: generic

      - name: Get patch level
        run: echo "TCL_PATCHLEVEL=$(cpp -dM generic/tcl.h | grep TCL_PATCH_LEVEL | awk -F'"' '/#define TCL_PATCH_LEVEL/ {print $2}')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 
            - mbwagner/tcl:${{ env.TCL_PATCHLEVEL }}-alpine
      
      - name: Build and push to Docker Hub (Alpine tag)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 
            - mbwagner/tcl:alpine
        if: github.ref == 'refs/heads/main'
        

